version: '3.8'

services:
  puddle:
    build: ./puddle
    command: "gunicorn puddle.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    env_file:
      - puddle/.env.dev


